version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: trading_system_db
    environment:
      POSTGRES_DB: trading_system
      POSTGRES_USER: trading_user
      POSTGRES_PASSWORD: your_secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: trading_system_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: