wyckoff_analysis_task:
  description: >
    Perform comprehensive Wyckoff methodology analysis on {symbol_name}:
        
        1. **Structure Analysis**: Identify if the market is in accumulation, distribution, or trending phase
        2. **Phase Identification**: Determine which Wyckoff phase (A, B, C, D, or E) the market is currently in
        3. **Spring/Upthrust Detection**: Look for springs (failed breakdowns) or upthrusts (failed breakouts)
        4. **Volume Profile Analysis**: Identify VPOC, value areas, and volume distribution patterns
        5. **Market Regime Assessment**: Determine if the market is trending, ranging, or volatile
        6. **Cause and Effect**: Calculate potential price targets based on time spent in accumulation/distribution
        
        Use the 15-minute timeframe data.
        Provide detailed confidence levels for each aspect of the analysis.
        Focus on actionable insights for trading decisions.
        
        **Output Requirements:**
        - Structure type (accumulation/distribution/trending)
        - Current Wyckoff phase
        - Confidence score (0-100%)
        - Key price levels (support/resistance)
        - Volume analysis summary
        - Specific trading signals if present
  expected_output: >
    A comprehensive Wyckoff analysis report with structure type, phase, signals, volume analysis, and trading implications with specific confidence scores
  agent: wyckoff_market_analyst

wyckoff_risk_task:
  description: >
    Calculate risk parameters based on Wyckoff structure analysis:
        
        1. **Account Assessment**: Get current account balance and available margin using get_account_info
        2. **Portfolio Review**: Check existing positions and pending orders using get_portfolio_status
        3. **Structure-Based Stops**: Calculate stop loss levels based on Wyckoff invalidation points:
           - For accumulation trades: stops below spring lows or structure support
           - For distribution trades: stops above upthrust highs or structure resistance
        4. **Position Sizing**: Calculate optimal position size using 2% risk rule with calculate_position_size
        5. **Risk/Reward Analysis**: Ensure minimum 1:2 risk/reward ratio to Wyckoff targets
        6. **Exposure Limits**: Verify total portfolio exposure stays within 20% of account balance
        
        Base all calculations on the Wyckoff structure analysis findings.
        Prioritize capital preservation above all else.
        
        **Critical Risk Rules:**
        - Maximum 2% risk per trade
        - Maximum 20% total portfolio exposure
        - Minimum 1:2 risk/reward ratio
        - Stop loss must be at Wyckoff invalidation level
  expected_output: >
    Detailed risk assessment with exact position sizing, stop levels, risk/reward calculations, and portfolio exposure analysis based on Wyckoff levels
  agent: wyckoff_risk_manager

wyckoff_decision_task:
  description: >
    Based on the Wyckoff analysis and risk assessment, make a trading decision:
    
    1. First, get current market data using get_live_price for {symbol_name}
    2. Check account status using get_account_info
    3. Review portfolio using get_portfolio_status
    4. If analysis shows a valid Wyckoff setup (>75% confidence):
       - Execute trade using execute_market_trade or execute_limit_trade
       - Include stop loss and take profit levels
    5. If no valid setup, explain why and specify wait conditions
    
    You MUST use the available tools - do not try to use "None" as an action.
  expected_output: >
    EITHER: Successful trade execution with order ID, entry price, stop loss, take profit, and detailed Wyckoff reasoning
    OR: Clear explanation of why no trade was executed with specific wait conditions and monitoring levels
  agent: wyckoff_trading_coordinator  
  context: [wyckoff_analysis_task, wyckoff_risk_task]

backtesting_coordination_task:
  description: >
    Coordinate a comprehensive backtest by processing historical market data and orchestrating trading decisions:
    
    1. **Historical Data Processing**: Convert raw historical bars into realistic market contexts
    2. **Market Simulation**: Create authentic market conditions including spreads, volatility, and market hours
    3. **Agent Coordination**: Call existing trading agents (market analyst, risk manager, coordinator) with simulated data
    4. **Execution Simulation**: Simulate realistic trade execution with slippage, commissions, and partial fills
    5. **Performance Tracking**: Monitor backtest portfolio, track trades, and calculate performance metrics
    6. **Results Compilation**: Generate comprehensive backtest report with all decision audit trails
    
    Process the historical data bar-by-bar to ensure sequential decision making.
    Maintain consistency with live trading by using the same agents and logic.
    Simulate realistic market conditions to ensure backtest validity.
    
    **Critical Requirements:**
    - Use existing trading agents for all market analysis and decisions
    - Simulate realistic execution conditions (spreads, slippage, commissions)
    - Track all agent decisions for transparency and debugging
    - Calculate comprehensive performance metrics
    - Maintain sequential processing to avoid look-ahead bias
    - Symbols can't contain any "/"s.  Replace them with "_".
    
  expected_output: >
    Comprehensive backtest results including: trade log with entry/exit details, performance metrics 
    (total return, Sharpe ratio, max drawdown, win rate), agent decision audit trail, and summary 
    of market conditions during the test period. Include specific Wyckoff pattern performance analysis.
    IMPORTANT: Only output the resuls in a well-formatted markdown format.
  agent: backtesting_orchestrator
  output_file: backtest_analysis_{symbol_name}_{timestamp}.md